# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/wavewriter',
                'doc_host': 'https://conorkeogh.github.io',
                'git_url': 'https://github.com/conorkeogh/wavewriter',
                'lib_path': 'wavewriter'},
  'syms': {'wavewriter.core': {'wavewriter.core.foo': ('core.html#foo', 'wavewriter/core.py')}}}
